ignoredBuiltDependencies:
  - '@heroui/shared-utils'
  - contentlayer
  - contentlayer2
  - core-js
  - electron
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - bcrypt
